name: OIDC PoC
on:
  push
env:
  AWS_REGION : "ap-southeast-2"
  
permissions:
      id-token: write
      contents: write    # This is required for actions/checkout@v1
jobs:
  tests3ls:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::123723535948:role/github-actions-oidc/github-actions-dev-preprod-cicd
          role-session-name: testing-githubcomelduds
          aws-region: ${{ env.AWS_REGION }}
      - name: s3 ls
        run: |
          aws sts get-caller-identity
          aws s3 ls

